### ISSUE TITLE
Type in documentation Running tests from Commandline

### ISSUE THREAD

**Issue by Frogli** [suransys/omnistap#7]
On the page https://github.com/suransys/omnistap/wiki/Running-OmnisTAP-from-the-command-line

There is a type in the paragraph:

> gettests will list all tests the are available in the library whose startup task subclasses omnistap.kgTAPTask. 

This should be: gettests will list all tests **that** are available...

**Comment by barkingfoodog** [comment]
Fixed. Good catch!
